// <auto-generated />
using System;
using ApiTool.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiTool.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260518193354_AddDeletionStateMachine")]
    partial class AddDeletionStateMachine
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.CoordinatorJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AggregateResultId")
                        .HasColumnType("TEXT")
                        .HasColumnName("aggregate_result_id");

                    b.Property<string>("CollectionSha")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("collection_sha");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ShardCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Status");

                    b.HasIndex("OrgId", "CreatedAt");

                    b.ToTable("coordinator_jobs", (string)null);
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.CoordinatorShard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedWorker")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("assigned_worker");

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FailCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastHeartbeatAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PassCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("requests");

                    b.Property<string>("ResultJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("result");

                    b.Property<int>("ShardIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "ShardIndex")
                        .IsUnique();

                    b.HasIndex("Status", "LastHeartbeatAt");

                    b.ToTable("coordinator_shards", (string)null);
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.CustomRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PermissionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("permissions");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("OrgId", "Name")
                        .IsUnique();

                    b.ToTable("organization_custom_roles", (string)null);
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.DeletionReauthToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("consumed_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("issued_at");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("idx_deletion_reauth_tokens_active")
                        .HasFilter("\"consumed_at\" IS NULL");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("idx_deletion_reauth_tokens_hash");

                    b.HasIndex("UserId", "IssuedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_deletion_reauth_tokens_user");

                    b.ToTable("deletion_reauth_tokens", (string)null);
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.EmailVerificationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("consumed_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("issued_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("revoked_at");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("idx_email_verification_tokens_active")
                        .HasFilter("\"consumed_at\" IS NULL AND \"revoked_at\" IS NULL");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("idx_email_verification_tokens_hash");

                    b.HasIndex("UserId", "IssuedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_email_verification_tokens_user");

                    b.ToTable("email_verification_tokens", (string)null);
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.GitLabInstallation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("AccessTokenCiphertext")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("access_token_ciphertext");

                    b.Property<string>("AccessTokenKid")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("access_token_kid");

                    b.Property<DateTime?>("AccessTokenRevokedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("access_token_revoked_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<string>("GitLabBaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("gitlab_base_url");

                    b.Property<string>("GitLabCaBundle")
                        .HasColumnType("TEXT")
                        .HasColumnName("gitlab_ca_bundle");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("TEXT")
                        .HasColumnName("org_id");

                    b.Property<long>("ProjectId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("project_id");

                    b.Property<string>("ProjectPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("project_path");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<byte[]>("WebhookSecretCiphertext")
                        .HasColumnType("BLOB")
                        .HasColumnName("webhook_secret_ciphertext");

                    b.Property<DateTime?>("WebhookSecretRotatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("webhook_secret_rotated_at");

                    b.HasKey("Id");

                    b.HasIndex("OrgId", "ProjectId", "GitLabBaseUrl")
                        .IsUnique()
                        .HasDatabaseName("idx_gitlab_installations_org_project_base")
                        .HasFilter("\"deleted_at\" IS NULL");

                    b.ToTable("gitlab_installations", (string)null);
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.GitLabWebhookEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("event_type");

                    b.Property<string>("EventUuid")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("event_uuid");

                    b.Property<int>("FailureCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("failure_count");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("installation_id");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("processed_at");

                    b.Property<DateTime?>("QuarantinedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("quarantined_at");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("received_at");

                    b.HasKey("Id");

                    b.HasIndex("EventUuid")
                        .IsUnique()
                        .HasDatabaseName("idx_gitlab_webhook_events_uuid");

                    b.HasIndex("InstallationId");

                    b.ToTable("gitlab_webhook_events", (string)null);
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.GithubInstallation", b =>
                {
                    b.Property<long>("InstallationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("installation_id");

                    b.Property<string>("AccountLogin")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("account_login");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("account_type");

                    b.Property<long>("AppId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("app_id");

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("claimed_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("InstalledAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("installed_at");

                    b.Property<DateTime>("LastReconciledAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_reconciled_at");

                    b.Property<Guid?>("OrgId")
                        .HasColumnType("TEXT")
                        .HasColumnName("org_id");

                    b.Property<string>("RepoSelection")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("repo_selection");

                    b.Property<string>("RepoSetJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("repo_set");

                    b.Property<DateTime?>("SuspendedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("suspended_at");

                    b.HasKey("InstallationId");

                    b.HasIndex("AppId")
                        .HasDatabaseName("idx_github_installations_app");

                    b.HasIndex("InstallationId")
                        .HasDatabaseName("idx_github_installations_alive")
                        .HasFilter("\"deleted_at\" IS NULL");

                    b.HasIndex("OrgId")
                        .IsUnique()
                        .HasDatabaseName("idx_github_installations_org")
                        .HasFilter("\"deleted_at\" IS NULL AND \"org_id\" IS NOT NULL");

                    b.ToTable("github_installations", (string)null);
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.GithubWebhookEvent", b =>
                {
                    b.Property<Guid>("DeliveryId")
                        .HasColumnType("TEXT")
                        .HasColumnName("delivery_id");

                    b.Property<string>("Action")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attempt_count");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_error");

                    b.Property<DateTime?>("LastErrorAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_error_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("processed_at");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("received_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("DeliveryId");

                    b.HasIndex("EventType", "ReceivedAt")
                        .HasDatabaseName("idx_github_webhook_events_type_received");

                    b.HasIndex("Status", "ReceivedAt")
                        .HasDatabaseName("idx_github_webhook_events_status_received");

                    b.ToTable("github_webhook_events", (string)null);
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("AmountPaid")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AmountTotal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("HostedInvoiceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("StripeCustomerId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("StripeInvoiceId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("StripeSubscriptionId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StripeInvoiceId")
                        .IsUnique();

                    b.HasIndex("OrgId", "CreatedAt");

                    b.ToTable("invoices", (string)null);
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.NotificationDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AttemptedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResponseCode")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ResultId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RuleId");

                    b.HasIndex("OrgId", "AttemptedAt");

                    b.ToTable("notification_deliveries", (string)null);
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.NotificationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("OnEvents")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("OrgId", "Channel");

                    b.ToTable("notification_rules", (string)null);
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AuditLogRetentionDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(365)
                        .HasColumnName("audit_log_retention_days");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("settings");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.OrganizationAuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorEmail")
                        .HasMaxLength(320)
                        .HasColumnType("TEXT")
                        .HasColumnName("actor_email");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("failure_reason");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT")
                        .HasColumnName("ip_address");

                    b.Property<string>("NewStateJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("new_state");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload");

                    b.Property<string>("PreviousStateJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("previous_state");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER")
                        .HasColumnName("success");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("TEXT")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("target_type");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_agent");

                    b.HasKey("Id");

                    b.HasIndex("EventType");

                    b.HasIndex("OrgId", "CreatedAt");

                    b.ToTable("organization_audit_log", (string)null);
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.OrganizationInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailNormalized")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InvitedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSentAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RevokedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("SendCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("token_hash");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("OrgId", "EmailNormalized", "AcceptedAt", "RevokedAt");

                    b.ToTable("organization_invitations", (string)null);
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.OrganizationMember", b =>
                {
                    b.Property<Guid>("OrgId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("InvitedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PermissionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("permissions");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("TEXT")
                        .HasColumnName("role_id");

                    b.HasKey("OrgId", "UserId");

                    b.HasIndex("UserId");

                    b.HasIndex("OrgId", "Role");

                    b.ToTable("organization_members", (string)null);
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("consumed_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("issued_at");

                    b.Property<string>("RequesterIp")
                        .HasColumnType("TEXT")
                        .HasColumnName("requester_ip");

                    b.Property<string>("RequesterUa")
                        .HasColumnType("TEXT")
                        .HasColumnName("requester_ua");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("revoked_at");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("idx_password_reset_tokens_active")
                        .HasFilter("\"consumed_at\" IS NULL AND \"revoked_at\" IS NULL");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("idx_password_reset_tokens_hash");

                    b.HasIndex("UserId", "IssuedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_password_reset_tokens_user");

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.PaymentMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AttachedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DetachedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("ExpMonth")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ExpYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Last4")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StripeCustomerId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("StripePaymentMethodId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StripePaymentMethodId")
                        .IsUnique();

                    b.HasIndex("OrgId", "AttachedAt");

                    b.ToTable("payment_methods", (string)null);
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.PrCheck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnnotationsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("annotations");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<long?>("CheckRunId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("check_run_id");

                    b.Property<string>("Conclusion")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("conclusion");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailsUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("details_url");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("TEXT")
                        .HasColumnName("external_id");

                    b.Property<Guid?>("GitLabInstallationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("gitlab_installation_id");

                    b.Property<long?>("GitLabStatusId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("gitlab_status_id");

                    b.Property<string>("HeadSha")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .HasColumnName("head_sha");

                    b.Property<long?>("InstallationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("installation_id");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("last_error");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputSummary")
                        .HasColumnType("TEXT")
                        .HasColumnName("output_summary");

                    b.Property<string>("OutputText")
                        .HasColumnType("TEXT")
                        .HasColumnName("output_text");

                    b.Property<DateTime?>("PostedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("posted_at");

                    b.Property<DateTime?>("PostingStartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("posting_started_at");

                    b.Property<int>("Pr")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("github")
                        .HasColumnName("provider");

                    b.Property<string>("Repo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResultId")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("idx_pr_checks_external_id");

                    b.HasIndex("GitLabInstallationId");

                    b.HasIndex("Provider")
                        .HasDatabaseName("idx_pr_checks_provider");

                    b.HasIndex("OrgId", "CreatedAt");

                    b.ToTable("pr_checks", null, t =>
                        {
                            t.HasCheckConstraint("ck_pr_checks_provider", "\"provider\" IN ('github', 'gitlab')");
                        });
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("device_id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("TEXT")
                        .HasColumnName("family_id");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("issued_at");

                    b.Property<string>("LastUsedIp")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_used_ip");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("parent_id");

                    b.Property<string>("RevokeReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("revoke_reason");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("revoked_at");

                    b.Property<DateTime?>("RotatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("rotated_at");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("token_hash");

                    b.Property<string>("UserAgent")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("idx_refresh_tokens_family");

                    b.HasIndex("ParentId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "DeviceId")
                        .HasDatabaseName("idx_refresh_tokens_user_device");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.Result", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CollectionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FailCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GitSha")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PassCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RunAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SkippedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TriggeredBy")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UploadedBy");

                    b.HasIndex("OrgId", "CreatedAt");

                    b.ToTable("results", (string)null);
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.ResultItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Method")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("method");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PathTemplate")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("path_template");

                    b.Property<string>("RequestUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("request_url");

                    b.Property<Guid>("ResultId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResultId", "Ordinal");

                    b.HasIndex("Status", "Method", "PathTemplate")
                        .HasDatabaseName("IX_result_items_Status_Method_PathTemplate");

                    b.ToTable("result_items", (string)null);
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CollectionRef")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastRunAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextRunAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("UTC");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Enabled", "NextRunAt");

                    b.HasIndex("OrgId", "Name")
                        .IsUnique();

                    b.ToTable("schedules", (string)null);
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.ScheduledRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClaimDeadline")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClaimToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimedByWorker")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastHeartbeatAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResultId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastHeartbeatAt")
                        .HasDatabaseName("IX_scheduled_runs_LastHeartbeatAt");

                    b.HasIndex("ResultId");

                    b.HasIndex("ScheduleId", "CreatedAt");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("IX_scheduled_runs_Status_CreatedAt");

                    b.ToTable("scheduled_runs", (string)null);
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.SigningKey", b =>
                {
                    b.Property<string>("Kid")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("kid");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("algorithm");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("KmsKeyId")
                        .HasColumnType("TEXT")
                        .HasColumnName("kms_key_id");

                    b.Property<DateTime?>("PromotedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("promoted_at");

                    b.Property<string>("PublicKeyJwkJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("public_key_jwk");

                    b.Property<DateTime?>("RetiringAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("retiring_at");

                    b.Property<string>("RevokeReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("revoke_reason");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Kid");

                    b.HasIndex("Status")
                        .IsUnique()
                        .HasDatabaseName("idx_signing_keys_next")
                        .HasFilter("\"status\" = 'next'");

                    b.ToTable("signing_keys", (string)null);
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.SsoCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicCertPem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrgId", "Kid")
                        .IsUnique();

                    b.ToTable("sso_credentials", (string)null);
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.StripeWebhookEvent", b =>
                {
                    b.Property<string>("EventId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("event_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attempt_count");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_error");

                    b.Property<DateTime?>("LastErrorAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_error_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("processed_at");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("received_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("EventId");

                    b.HasIndex("EventType", "ReceivedAt")
                        .HasDatabaseName("idx_webhook_events_type_received");

                    b.HasIndex("Status", "ReceivedAt")
                        .HasDatabaseName("idx_webhook_events_status_received");

                    b.ToTable("stripe_webhook_events", (string)null);
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("CancelAtPeriodEnd")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CanceledAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CurrentPeriodEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CurrentPeriodStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("Interval")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SeatCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeatLimit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("StripeCustomerEmail")
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("StripeSubscriptionId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrgId")
                        .IsUnique();

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.TeamVault", b =>
                {
                    b.Property<Guid>("OrgId")
                        .HasColumnType("TEXT")
                        .HasColumnName("org_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<string>("TemplateJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("template_jsonb");

                    b.Property<string>("TemplateYaml")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("template_yaml");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("OrgId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("idx_team_vaults_updated");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("team_vaults", (string)null);
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.Trial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("consumed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<string>("Feature")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("feature");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("granted_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<DateTime?>("Notified1DayAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("notified_1day_at");

                    b.Property<DateTime?>("Notified3DayAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("notified_3day_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("idx_trials_notify_1day")
                        .HasFilter("\"notified_1day_at\" IS NULL AND \"consumed_at\" IS NULL");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_trials_user");

                    b.HasIndex("UserId", "Feature")
                        .IsUnique()
                        .HasDatabaseName("idx_trials_user_feature");

                    b.ToTable("trials", null, t =>
                        {
                            t.HasCheckConstraint("ck_trials_kind", "\"kind\" IN ('full_initial', 'ondemand', 'preempted_by_subscription')");
                        });
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AnonymisedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("anonymised_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("email_verified");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_admin");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("PendingDeletionAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("pending_deletion_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.UserExportRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("failure_reason");

                    b.Property<string>("ObjectKey")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("object_key");

                    b.Property<DateTime?>("ReadyAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("ready_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_user_export_requests_user_created");

                    b.ToTable("user_export_requests", (string)null);
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.CoordinatorJob", b =>
                {
                    b.HasOne("ApiTool.Backend.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiTool.Backend.Data.Entities.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.CoordinatorShard", b =>
                {
                    b.HasOne("ApiTool.Backend.Data.Entities.CoordinatorJob", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.CustomRole", b =>
                {
                    b.HasOne("ApiTool.Backend.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiTool.Backend.Data.Entities.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.DeletionReauthToken", b =>
                {
                    b.HasOne("ApiTool.Backend.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.EmailVerificationToken", b =>
                {
                    b.HasOne("ApiTool.Backend.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.GitLabInstallation", b =>
                {
                    b.HasOne("ApiTool.Backend.Data.Entities.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.GitLabWebhookEvent", b =>
                {
                    b.HasOne("ApiTool.Backend.Data.Entities.GitLabInstallation", null)
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.GithubInstallation", b =>
                {
                    b.HasOne("ApiTool.Backend.Data.Entities.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.Invoice", b =>
                {
                    b.HasOne("ApiTool.Backend.Data.Entities.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.NotificationDelivery", b =>
                {
                    b.HasOne("ApiTool.Backend.Data.Entities.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiTool.Backend.Data.Entities.NotificationRule", null)
                        .WithMany()
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.NotificationRule", b =>
                {
                    b.HasOne("ApiTool.Backend.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiTool.Backend.Data.Entities.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.Organization", b =>
                {
                    b.HasOne("ApiTool.Backend.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.OrganizationAuditLogEntry", b =>
                {
                    b.HasOne("ApiTool.Backend.Data.Entities.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.OrganizationInvitation", b =>
                {
                    b.HasOne("ApiTool.Backend.Data.Entities.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.OrganizationMember", b =>
                {
                    b.HasOne("ApiTool.Backend.Data.Entities.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiTool.Backend.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("ApiTool.Backend.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.PaymentMethod", b =>
                {
                    b.HasOne("ApiTool.Backend.Data.Entities.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.PrCheck", b =>
                {
                    b.HasOne("ApiTool.Backend.Data.Entities.GitLabInstallation", null)
                        .WithMany()
                        .HasForeignKey("GitLabInstallationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ApiTool.Backend.Data.Entities.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.RefreshToken", b =>
                {
                    b.HasOne("ApiTool.Backend.Data.Entities.RefreshToken", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ApiTool.Backend.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.Result", b =>
                {
                    b.HasOne("ApiTool.Backend.Data.Entities.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiTool.Backend.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.ResultItem", b =>
                {
                    b.HasOne("ApiTool.Backend.Data.Entities.Result", null)
                        .WithMany()
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.Schedule", b =>
                {
                    b.HasOne("ApiTool.Backend.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiTool.Backend.Data.Entities.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.ScheduledRun", b =>
                {
                    b.HasOne("ApiTool.Backend.Data.Entities.Result", null)
                        .WithMany()
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ApiTool.Backend.Data.Entities.Schedule", null)
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.SsoCredential", b =>
                {
                    b.HasOne("ApiTool.Backend.Data.Entities.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.Subscription", b =>
                {
                    b.HasOne("ApiTool.Backend.Data.Entities.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.TeamVault", b =>
                {
                    b.HasOne("ApiTool.Backend.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiTool.Backend.Data.Entities.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiTool.Backend.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.Trial", b =>
                {
                    b.HasOne("ApiTool.Backend.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiTool.Backend.Data.Entities.UserExportRequest", b =>
                {
                    b.HasOne("ApiTool.Backend.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
